version: '3'

services:
  mjml_service:
    # hostname: 'mjml.kytes.io'
    container_name: "mjml.kytes.io"
    # image: theyellowdevopsteam_io/the-yellow-vote:0.0.0
    image: jbl/mjml:1.0.0
    build: 
      context: ./docker/construction/serveur
#       args:
        # ENV. USINE LOGICIELLE JAUNE
        # ADD .cle.privee.usine.jaune ./.secret
        # - YELLOW_GIT_SECRET=$YELLOW_GIT_SECRET
        
# + / - => Les volumes me posent le problème suivant : ce n'est pas le user root qui agit dans le conteneur, et
#          donc conflit de droits avec le SGF de l'hôte docker
#     volumes:
#       - $AVOIR:$IN_CONTAINER_WHATEVER_DIRECTORY:rw
#     environment:
#       - YELLOW_OPERATOR_USER_NAME=$YELLOW_OPERATOR_USER_NAME
    ports:
      # - $NUM_PORT_ECOUTE_FRONTEND_APPLI_VOTE:$NUM_PORT_ECOUTE_FRONTEND_APPLI_VOTE_IN_CONTAINER
      - 5698:3000
    expose:
      - 3000/tcp
      # - 8000/tcp
      # pas de dépendance directe entre front et back : 
      # => le front est une SPA,si elle peut être servie, elle le sera, et elle affichera une belle page "patientez, le backend s'initialise..."
#     depends_on:
      # - the_yellow_vote_back
      # + Depuis utilisation d'un build image custom mongo avec HEALTHCHECK pour le
      # + conteneur 'mongo-init-replica', cf. ./mongo-init-replica/construction/replicaset-health-check
      # + mais plus depusi l'avènement du soudeur
      # - mongo-init-replica
    networks:
      - "reseau_devops"
    restart: always
networks:
  # donc dans le fichier ["./.env]", on doit tropuver la déclaration de variable [NOM_DU_RESEAU_DEMO_MJML=reseau_vote_jaune]
  reseau_devops:
    driver: bridge
